### ISSUE TITLE
How to set or support angle brackets? 

### ISSUE THREAD

**Issue by BabyMelvin** [tal7aouy/vscode-rainbow-brackets#3]
How to set or support angle brackets? I was always confused by the multi long generic types declared in `Rust`.
Thanks a lot.

**Comment by brady2037** [comment]
Extension Settings -> Edit in setting.json -> RainbowBrackets.consecutivePairColors ,  add "<>"

```
"RainbowBrackets.consecutivePairColors": [
    "()",
    "[]",
    "{}",
    "<>",
    ["teal", "yellow", "tomato"],
    "Revioletd"
  ],
```
